### ISSUE TITLE
Prisma DMMF

### ISSUE THREAD

**Issue by tika** [alii/trisma#1]
Convert a Prisma DMMF into a working Prisma Client (including migrations, studio, etc)

**Comment by alii** [comment]
Great

**Comment by alii** [comment]
I am working on this now 😁

**Comment by robertt** [comment]
Imo this would greatly effect the library and would ruin it's functionality. Strong 👎 from me.

**Comment by tika** [comment]
"Nothing", used as a pronoun subject, is the absence of a something or particular thing that one might expect or desire to be present ("We found nothing", "Nothing was there") or the inactivity of a thing or things that are usually or could be active ("Nothing moved", "Nothing happened"). As a predicate or complement "nothing" is the absence of meaning, value, worth, relevance, standing, or significance ("It is a tale/ Told by an idiot, full of sound and fury,/ Signifying nothing"; "The affair meant nothing"; "I'm nothing in their eyes").[1] "Nothingness" is a philosophical term for the general state of nonexistence, sometimes reified as a domain or dimension into which things pass when they cease to exist or out of which they may come to exist, e.g., God is understood to have created the universe ex nihilo, "out of nothing".[1][2]

**Comment by tika** [comment]
Nvm we don't need this

**Comment by alii** [comment]
👍

**Comment by robertt** [comment]
> Nvm we don't need this

You really have the audacity to say something like this? In 2021? Disgusting. #killallmen
